# Generated by Django 5.0.7 on 2025-10-31 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
        ("productos", "0002_claseproducto_laboratorio_subcategoria_and_more"),
        ("proveedores", "0002_alter_proveedor_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ubicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("sucursal", "Sucursal"),
                            ("bodega", "Bodega"),
                            ("almacen", "Almacén"),
                            ("deposito", "Depósito"),
                        ],
                        default="sucursal",
                        max_length=15,
                    ),
                ),
                ("direccion", models.TextField(blank=True)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("responsable", models.CharField(blank=True, max_length=100)),
                ("activo", models.BooleanField(default=True)),
                ("es_principal", models.BooleanField(default=False)),
                ("creadoDate", models.DateTimeField(auto_now_add=True)),
                ("editadoDate", models.DateTimeField(auto_now=True)),
                ("anulado", models.BooleanField(default=False)),
                (
                    "creadoPor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ubicaciones_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "editadoPor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ubicaciones_editadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ubicación",
                "verbose_name_plural": "Ubicaciones",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TransferenciaStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_transferencia", models.CharField(max_length=50, unique=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("fecha_recepcion", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_transito", "En Tránsito"),
                            ("recibida", "Recibida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=15,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("reposicion", "Reposición Automática"),
                            ("redistribucion", "Redistribución"),
                            ("emergencia", "Emergencia"),
                        ],
                        default="manual",
                        max_length=15,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("motivo", models.CharField(blank=True, max_length=200)),
                ("creadoDate", models.DateTimeField(auto_now_add=True)),
                ("editadoDate", models.DateTimeField(auto_now=True)),
                ("anulado", models.BooleanField(default=False)),
                (
                    "creadoPor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferencias_auditoria_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "editadoPor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transferencias_auditoria_editadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_creacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferencias_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_envio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferencias_enviadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_recepcion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferencias_recibidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ubicacion_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferencias_recibidas",
                        to="inventario.ubicacion",
                    ),
                ),
                (
                    "ubicacion_origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferencias_enviadas",
                        to="inventario.ubicacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transferencia de Stock",
                "verbose_name_plural": "Transferencias de Stock",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="OrdenCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_orden", models.CharField(max_length=50, unique=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("fecha_entrega_esperada", models.DateField(blank=True, null=True)),
                ("fecha_entrega_real", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("enviada", "Enviada"),
                            ("confirmada", "Confirmada"),
                            ("recibida_parcial", "Recibida Parcial"),
                            ("recibida_completa", "Recibida Completa"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("normal", "Normal"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "impuesto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("generada_automaticamente", models.BooleanField(default=False)),
                ("creadoDate", models.DateTimeField(auto_now_add=True)),
                ("editadoDate", models.DateTimeField(auto_now=True)),
                ("anulado", models.BooleanField(default=False)),
                (
                    "creadoPor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_auditoria_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "editadoPor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordenes_auditoria_editadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_compra",
                        to="proveedores.proveedor",
                    ),
                ),
                (
                    "usuario_creacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_envio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_enviadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ubicacion_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes_recibidas",
                        to="inventario.ubicacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Compra",
                "verbose_name_plural": "Órdenes de Compra",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="DetalleOrdenCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_solicitada", models.PositiveIntegerField()),
                ("cantidad_recibida", models.PositiveIntegerField(default=0)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "descuento_linea",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("stock_actual", models.PositiveIntegerField(default=0)),
                ("stock_minimo", models.PositiveIntegerField(default=0)),
                ("motivo_solicitud", models.TextField(blank=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="productos.producto",
                    ),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="inventario.ordencompra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Orden de Compra",
                "verbose_name_plural": "Detalles de Órdenes de Compra",
                "unique_together": {("orden", "producto")},
            },
        ),
        migrations.CreateModel(
            name="DetalleTransferencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("cantidad_recibida", models.PositiveIntegerField(default=0)),
                ("stock_origen_antes", models.PositiveIntegerField(default=0)),
                ("stock_destino_antes", models.PositiveIntegerField(default=0)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="productos.producto",
                    ),
                ),
                (
                    "transferencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="inventario.transferenciastock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Transferencia",
                "verbose_name_plural": "Detalles de Transferencias",
                "unique_together": {("transferencia", "producto")},
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_minimo", models.PositiveIntegerField(default=0)),
                ("stock_maximo", models.PositiveIntegerField(default=0)),
                ("punto_reorden", models.PositiveIntegerField(default=0)),
                ("cantidad_reorden", models.PositiveIntegerField(default=0)),
                ("generar_orden_automatica", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                ("creadoDate", models.DateTimeField(auto_now_add=True)),
                ("editadoDate", models.DateTimeField(auto_now=True)),
                ("anulado", models.BooleanField(default=False)),
                (
                    "creadoPor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="config_stock_auditoria_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "editadoPor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_stock_auditoria_editadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuraciones_stock",
                        to="productos.producto",
                    ),
                ),
                (
                    "proveedor_preferido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="proveedores.proveedor",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ubicacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuraciones_stock",
                        to="inventario.ubicacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Stock",
                "verbose_name_plural": "Configuraciones de Stock",
                "ordering": ["producto__nombre"],
                "unique_together": {("producto", "ubicacion")},
            },
        ),
    ]
