# Generated by Django 5.0.7 on 2025-10-24 17:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo de la empresa', max_length=200, verbose_name='Nombre de la empresa')),
                ('rtn', models.CharField(blank=True, help_text='Registro Tributario Nacional', max_length=20, verbose_name='RTN')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('sitio_web', models.URLField(blank=True, verbose_name='Sitio web')),
                ('cai', models.CharField(blank=True, help_text='Código de Autorización de Impresión', max_length=50, verbose_name='CAI')),
                ('rango_inicial', models.CharField(blank=True, help_text='Número inicial del rango de facturación', max_length=20, verbose_name='Rango inicial')),
                ('rango_final', models.CharField(blank=True, help_text='Número final del rango de facturación', max_length=20, verbose_name='Rango final')),
                ('fecha_limite_emision', models.DateField(blank=True, help_text='Fecha límite para emisión de facturas', null=True, verbose_name='Fecha límite de emisión')),
                ('moneda', models.CharField(default='Dólares', help_text='Nombre de la moneda utilizada', max_length=50, verbose_name='Moneda')),
                ('simbolo_moneda', models.CharField(default='$', help_text='Símbolo utilizado para la moneda', max_length=5, verbose_name='Símbolo de moneda')),
                ('impuesto_defecto', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Porcentaje de impuesto por defecto', max_digits=5, verbose_name='Impuesto por defecto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuraciones de Empresa',
            },
        ),
    ]
