# Generated by Django 5.0.7 on 2026-01-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_configuracionempresa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auditoria",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("id_usuario", models.IntegerField(db_column="idUsuario")),
                ("usuario", models.CharField(blank=True, max_length=100, null=True)),
                ("modulo", models.CharField(max_length=100)),
                ("accion", models.CharField(blank=True, max_length=30, null=True)),
                ("entidad", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "id_entidad",
                    models.BigIntegerField(
                        blank=True, db_column="idEntidad", null=True
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("ip", models.CharField(blank=True, max_length=45, null=True)),
                ("host", models.CharField(blank=True, max_length=100, null=True)),
                ("origen", models.CharField(blank=True, max_length=50, null=True)),
                ("extra", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "auditoria",
                "ordering": ["-fecha"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Impuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20)),
                ("nombre", models.CharField(max_length=100)),
                ("porcentaje", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "vigenteDesde",
                    models.DateField(blank=True, db_column="vigenteDesde", null=True),
                ),
                (
                    "vigenteHasta",
                    models.DateField(blank=True, db_column="vigenteHasta", null=True),
                ),
                ("activo", models.BooleanField(default=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Impuesto",
                "verbose_name_plural": "Impuestos",
                "db_table": "impuestos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "creado_por",
                    models.PositiveIntegerField(
                        blank=True, db_column="creadoPor", null=True
                    ),
                ),
                ("creado_date", models.DateTimeField(db_column="creadoDate")),
                (
                    "editado_por",
                    models.PositiveIntegerField(
                        blank=True, db_column="editadoPor", null=True
                    ),
                ),
                (
                    "editado_date",
                    models.DateTimeField(
                        blank=True, db_column="editadoDate", null=True
                    ),
                ),
                ("anulado", models.BooleanField(default=False)),
                (
                    "anulado_por",
                    models.PositiveIntegerField(
                        blank=True, db_column="anuladoPor", null=True
                    ),
                ),
                (
                    "anulado_date",
                    models.DateTimeField(
                        blank=True, db_column="anuladoDate", null=True
                    ),
                ),
            ],
            options={
                "db_table": "roles",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RolPermiso",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("modulo", models.CharField(max_length=50)),
                ("permiso", models.CharField(max_length=100)),
                (
                    "puede_crear",
                    models.BooleanField(db_column="puede_crear", default=False),
                ),
                (
                    "puede_editar",
                    models.BooleanField(db_column="puede_editar", default=False),
                ),
                (
                    "puede_eliminar",
                    models.BooleanField(db_column="puede_eliminar", default=False),
                ),
                ("puede_ver", models.BooleanField(db_column="puede_ver", default=True)),
                (
                    "creado_por",
                    models.PositiveIntegerField(
                        blank=True, db_column="creadoPor", null=True
                    ),
                ),
                ("creado_date", models.DateTimeField(db_column="creadoDate")),
                (
                    "editado_por",
                    models.PositiveIntegerField(
                        blank=True, db_column="editadoPor", null=True
                    ),
                ),
                (
                    "editado_date",
                    models.DateTimeField(
                        blank=True, db_column="editadoDate", null=True
                    ),
                ),
            ],
            options={
                "db_table": "rol_permisos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UsuarioSistema",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre_usuario",
                    models.CharField(
                        db_column="nombreUsuario", max_length=50, unique=True
                    ),
                ),
                (
                    "contrasena_hash",
                    models.CharField(db_column="contrasenaHash", max_length=255),
                ),
                (
                    "nombre_completo",
                    models.CharField(db_column="nombreCompleto", max_length=150),
                ),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "tipo_menu",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("horizontal", "Horizontal"),
                            ("vertical", "Vertical"),
                        ],
                        db_column="tipoMenu",
                        default="horizontal",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "creado_por",
                    models.PositiveIntegerField(
                        blank=True, db_column="creadoPor", null=True
                    ),
                ),
                ("creado_date", models.DateTimeField(db_column="creadoDate")),
                (
                    "editado_por",
                    models.PositiveIntegerField(
                        blank=True, db_column="editadoPor", null=True
                    ),
                ),
                (
                    "editado_date",
                    models.DateTimeField(
                        blank=True, db_column="editadoDate", null=True
                    ),
                ),
                ("anulado", models.BooleanField(default=False)),
                (
                    "anulado_por",
                    models.PositiveIntegerField(
                        blank=True, db_column="anuladoPor", null=True
                    ),
                ),
                (
                    "anulado_date",
                    models.DateTimeField(
                        blank=True, db_column="anuladoDate", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario del Sistema",
                "verbose_name_plural": "Usuarios del Sistema",
                "db_table": "usuarios",
                "ordering": ["nombre_completo"],
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="configuracionempresa",
            options={
                "managed": False,
                "verbose_name": "Configuración de Empresa",
                "verbose_name_plural": "Configuraciones de Empresa",
            },
        ),
        migrations.AlterModelOptions(
            name="perfilusuario",
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuario",
            },
        ),
        migrations.RemoveField(
            model_name="perfilusuario",
            name="fecha_nacimiento",
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="perfiles/"),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("vendedor", "Vendedor"),
                    ("cajero", "Cajero"),
                    ("gerente", "Gerente"),
                ],
                default="vendedor",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="telefono",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
