# Generated by Django 5.0.7 on 2025-10-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClaseProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Clase de Producto",
                "verbose_name_plural": "Clases de Producto",
                "db_table": "clases_producto",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Laboratorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Laboratorio",
                "verbose_name_plural": "Laboratorios",
                "db_table": "laboratorios",
                "ordering": ["nombre"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Subcategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Subcategoría",
                "verbose_name_plural": "Subcategorías",
                "db_table": "subcategorias",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SubnivelProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Subnivel de Producto",
                "verbose_name_plural": "Subniveles de Producto",
                "db_table": "subniveles_producto",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Tipo de Producto",
                "verbose_name_plural": "Tipos de Producto",
                "db_table": "tipos_producto",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="categoria",
            options={
                "managed": False,
                "ordering": ["nombre"],
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.AlterModelOptions(
            name="marca",
            options={
                "managed": False,
                "ordering": ["nombre"],
                "verbose_name": "Marca",
                "verbose_name_plural": "Marcas",
            },
        ),
        migrations.AlterModelOptions(
            name="producto",
            options={
                "managed": False,
                "ordering": ["nombre"],
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
            },
        ),
    ]
