# Generated by Django 5.0.7 on 2025-10-24 19:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de emisión de la cotización', verbose_name='Fecha de Cotización'),
        ),
    ]
