# Generated by Django 5.0.7 on 2025-10-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_cotizacion_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='descuento',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='descuento_global',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento Global %'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='referencia_cliente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia del Cliente'),
        ),
    ]
