# Generated by Django 5.0.7 on 2025-10-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
