# Generated by Django 5.0.7 on 2026-01-04 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0003_arqueo_caja"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArqueoCaja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idCierreCaja", models.IntegerField(db_column="idCierreCaja")),
                (
                    "billete_100",
                    models.IntegerField(db_column="billete_100", default=0),
                ),
                ("billete_50", models.IntegerField(db_column="billete_50", default=0)),
                ("billete_20", models.IntegerField(db_column="billete_20", default=0)),
                ("billete_10", models.IntegerField(db_column="billete_10", default=0)),
                ("billete_5", models.IntegerField(db_column="billete_5", default=0)),
                ("moneda_1", models.IntegerField(db_column="moneda_1", default=0)),
                ("moneda_050", models.IntegerField(db_column="moneda_050", default=0)),
                ("moneda_025", models.IntegerField(db_column="moneda_025", default=0)),
                ("moneda_010", models.IntegerField(db_column="moneda_010", default=0)),
                ("moneda_005", models.IntegerField(db_column="moneda_005", default=0)),
                ("moneda_001", models.IntegerField(db_column="moneda_001", default=0)),
                (
                    "total_billetes",
                    models.DecimalField(
                        db_column="total_billetes",
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                    ),
                ),
                (
                    "total_monedas",
                    models.DecimalField(
                        db_column="total_monedas",
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                    ),
                ),
                (
                    "total_general",
                    models.DecimalField(
                        db_column="total_general",
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                    ),
                ),
                (
                    "notas_arqueo",
                    models.TextField(blank=True, db_column="notas_arqueo", null=True),
                ),
                ("creadoPor", models.IntegerField(db_column="creadoPor")),
                (
                    "creadoDate",
                    models.DateTimeField(auto_now_add=True, db_column="creadoDate"),
                ),
            ],
            options={
                "verbose_name": "Arqueo de Caja",
                "verbose_name_plural": "Arqueos de Caja",
                "db_table": "arqueos_caja",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="aperturacaja",
            options={
                "managed": False,
                "ordering": ["-FechaApertura"],
                "verbose_name": "Apertura de Caja (Legacy)",
                "verbose_name_plural": "Aperturas de Caja (Legacy)",
            },
        ),
        migrations.AlterModelOptions(
            name="caja",
            options={
                "managed": False,
                "ordering": ["nombre"],
                "verbose_name": "Caja",
                "verbose_name_plural": "Cajas",
            },
        ),
        migrations.AlterModelOptions(
            name="cierrecaja",
            options={
                "managed": False,
                "ordering": ["-fechaApertura"],
                "verbose_name": "Apertura/Cierre de Caja",
                "verbose_name_plural": "Aperturas/Cierres de Caja",
            },
        ),
        migrations.CreateModel(
            name="CierrePeriodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("MENSUAL", "Cierre Mensual"),
                            ("ANUAL", "Cierre Anual"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "mes",
                    models.IntegerField(
                        blank=True, help_text="1-12 para cierre mensual", null=True
                    ),
                ),
                ("anio", models.IntegerField(help_text="Año del cierre")),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("fecha_cierre", models.DateTimeField(auto_now_add=True)),
                (
                    "total_ventas",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_compras",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_gastos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_ingresos_extra",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "valor_inventario_costo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "valor_inventario_venta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "archivo_reporte",
                    models.FileField(
                        blank=True, null=True, upload_to="cierres_periodos/"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cierre de Periodo",
                "verbose_name_plural": "Cierres de Periodo",
                "db_table": "cierres_periodo",
                "ordering": ["-anio", "-mes"],
                "unique_together": {("tipo", "mes", "anio")},
            },
        ),
        migrations.DeleteModel(
            name="MovimientoCaja",
        ),
    ]
