# Generated by Django 5.0.7 on 2025-10-24 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo_documento', models.CharField(choices=[('rtn', 'RTN'), ('identidad', 'Tarjeta de Identidad'), ('pasaporte', 'Pasaporte')], default='rtn', max_length=20)),
                ('numero_documento', models.CharField(max_length=50, unique=True)),
                ('nombre_comercial', models.CharField(max_length=200)),
                ('razon_social', models.CharField(blank=True, max_length=200)),
                ('contacto_principal', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Número de teléfono debe tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dias_credito', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre_comercial'],
            },
        ),
    ]
