# Generated by Django 5.0.7 on 2025-10-31 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("proveedores", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proveedor",
            options={
                "managed": False,
                "ordering": ["razon_social"],
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
            },
        ),
    ]
